name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [8.x, 9.x, 10.x, 11.x, 12.x, 13.x, 14.x, 15.x]

    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.os }}-${{ matrix.node-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
